server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wechat361/springcloud2023-config.git
          search-paths:
            - springcloud2023-config
          username: ctwechat@163.com
          password: CTxidianzi123
      # 读取Git上的master分支
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka  # 单机版注册方式
      #defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka, http://eureka7003.com:7003/eureka  # 集群版注册方式
